Copy namespaces into `clj-commons` and update `primitive-math` dependency
clj-commons/byte-streams pull request #54
Opened 2022-04-04 21:22 UTC by skynet-gh

Fixes issues with single segment namespaces.
Keep existing namespaces for compatibility.

Updates `primitive-math` dependency which was updated similarly in https://github.com/clj-commons/primitive-math/pull/14\

Tests:
```
$ lein test
Compiling 3 source files to /home/skynet/git/byte-streams/target/classes

lein test byte-streams-simple-check
{:result true, :num-tests 10000, :seed 1649107149557, :time-elapsed-ms 594, :test-var "equivalent-comparison"}

lein test byte-streams-test

lein test clj-commons.byte-streams-simple-check
{:result true, :num-tests 10000, :seed 1649107189494, :time-elapsed-ms 372, :test-var "equivalent-comparison"}

lein test clj-commons.byte-streams-test

lein test pushback-stream-test

Ran 15 tests containing 1003 assertions.
0 failures, 0 errors
```

2022-04-06 10:29 UTC, KingMob requested changes
Looks really good so far. I have two requests:

1. Can you add the [:superseded-by and :no-doc metadata](https://guide.clojure.style/#superseded-by) to the old namespaces?
2. I don't think byte-streams is ready for 1.0.0 just yet. The next release will probably be 0.3.0, but for now, can you change the `:deprecated` value to just `true`, and I'll update it when ready?

2022-04-06 21:08 UTC, skynet-gh commented
@KingMob sure no problem, I think I've updated all the namespaces as you describe.

2022-04-07 04:16 UTC, KingMob requested changes
Superseded is spelled without a "c" 😄 

`:superseded-by`

2022-04-07 04:24 UTC, skynet-gh commented
@KingMob whoops! fixed

2022-04-07 13:52 UTC, KingMob commented
Sweet! I’ll double-check this weekend when I’m free, but I think that’s it.

2022-04-09 06:35 UTC, KingMob approved these changes

2022-04-09 06:36 UTC, merged