Drop type-hints from `assoc-conversion` to work around AOT issue
clj-commons/byte-streams pull request #69
Opened 2023-01-24 14:07 UTC by DerGuteMoritz

Since this function is usually not called at runtime, the reflection performance penalty should be tolerable.

Fixes #68

2023-01-25 06:35 UTC, KingMob commented
Does it also fix #34?

2023-01-25 06:39 UTC, KingMob requested changes
Can you make Eastwood stop complaining about the changes? https://github.com/jonase/eastwood#ignored-faults

2023-01-26 14:06 UTC, DerGuteMoritz commented
> Does it also fix #34?

Pretty sure it would (this patch was derived from the workaround in that ticket's description). However, according to https://github.com/clj-commons/byte-streams/issues/34#issuecomment-1138168703 it wasn't reproducible anymore in that particular context so I didn't try anymore.

> Can you make Eastwood stop complaining about the changes?

Done!

2023-01-27 05:33 UTC, KingMob approved these changes
Really wish Eastwood was configurable for _names_, not just files/lines/cols, but...

2023-02-06 18:51 UTC, DerGuteMoritz commented
Indeed, that's unfortunate :shrug: 

Note that I don't have merge rights myself here so you'll have to do the honors :slightly_smiling_face:

2023-02-07 06:00 UTC, KingMob commented
Dammit, let me see about adding you as a contributor

2023-02-07 06:02 UTC, KingMob commented
@DerGuteMoritz Try merging now

2023-02-08 11:59 UTC, merged

2023-02-08 11:59 UTC, DerGuteMoritz commented
Thanks! :pray: